docs_dir: "zh-tw"
site_name: "OSCVPass 開源貢獻者申請專案"
site_url: "https://oscvpass.ocf.tw"
site_description: 參與開源活動或貢獻活動證明
site_author: 財團法人開放文化基金會 OCF
repo_url: https://github.com/ocftw/OSCVPass
repo_name: ocftw/OSCVPass
copyright: "CC-BY 4.0 OSCVPass Project"
edit_uri: https://github.com/ocftw/OSCVPass/edit/main/src/site_docs/zh-tw

nav:
  - 專案說明:
      - index.md
      - apply.md
      - open-source-definition.md
      - license.md
      - non-software-license.md
      - 1.0 -> 2.0:
          - v2/index.md
      - 合作夥伴:
          - partner/index.md
  - 最新資訊:
      - blog/index.md
  - 已核准專案:
      - approved/index.md
      - approved/open-source.md
      - approved/community.md
      - approved/program.md
      - approved/security-web3.md
      - approved/language.md
      - approved/l10n.md
      - approved/image-sound.md
      - approved/app.md
      - approved/chatbot-api.md
      - approved/linux-kernel.md
      - approved/pull-request.md
  - 志工、實習:
      - volunteer/index.md
      - volunteer/internship.md
theme:
  name: material
  icon:
    logo: material/passport
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: lime
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  language: "zh-TW"
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.view
    - content.action.edit
    - content.tooltips
    - content.footnote.tooltips
  custom_dir: zh-tw/overrides
extra:
  analytics:
    provider: google
    property: G-CFKVL29PQR
  social:
    - icon: material/email-plus
      link: mailto:oscvpass@ocf.tw
    - icon: fontawesome/brands/github
      link: https://github.com/ocftw/OSCVPass
    - icon: material/home
      link: https://oscvpass.ocf.tw/
plugins:
  - search:
      lang:
        - zh
        - en
  - social:
      cards_layout_options:
        font_family: Noto Sans TC
        color: "#ffffff"
        background_color: "#009485"
  - privacy
  - git-revision-date-localized:
      type: iso_datetime
      locale: en
      enable_creation_date: true
      enable_parallel_processing: true
  - git-authors:
      show_contribution: true
      show_email_address: false
      show_line_count: true
  - blog:
      post_url_date_format: yyyy/MM
      post_url_format: "{date}/{slug}"
      archive: true
      categories: true
      categories_name: "文章類型"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
        as_update: git
      categories:
        - categories
        - tages
      pretty_print: false
      abstract_chars_count: -1
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
