docs_dir: "zh-tw"
site_name: "OSCVPass 開源貢獻者申請專案"
site_url: "https://oscvpass.ocf.tw"
site_description: 參與開源活動或貢獻活動證明
site_author: 財團法人開放文化基金會 OCF
repo_url: https://github.com/ocftw/OSCVPass
repo_name: ocftw/OSCVPass
copyright: "CC-BY 4.0 OSCVPass Project, 財團法人開放文化基金會 OCF"
edit_uri: https://github.com/ocftw/OSCVPass/tree/main/src/site_docs/zh-tw

nav:
  - 專案說明:
      - index.md
      - apply.md
      - volunteer.md
  - 已核准專案:
      - approved/index.md
      - approved/open-source.md
      - approved/community.md
      - approved/program.md
      - approved/security-web3.md
      - approved/language.md
      - approved/l10n.md
      - approved/image-sound.md
      - approved/app.md
      - approved/chatbot-api.md
      - approved/linux-kernel.md
      - approved/pull-request.md
theme:
  name: material
  language: zh-Hant
  icon:
    logo: material/passport
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.svg
  palette:
    primary: teal
    accent: indigo
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.action.view
    - content.action.edit
extra:
  analytics:
    provider: google
    property: G-CFKVL29PQR
  social:
    - icon: material/email-plus
      link: oscvpass@ocf.tw
    - icon: fontawesome/brands/github
      link: https://github.com/ocftw/OSCVPass
    - icon: material/home
      link: https://oscvpass.ocf.tw/
plugins:
  - search:
      lang:
        - zh
        - en
  - privacy
  - git-revision-date-localized:
      type: iso_datetime
      locale: en
      enable_creation_date: true
      enable_parallel_processing: true
  - git-authors:
      show_contribution: true
      show_email_address: false
      show_line_count: true
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
